services:
  ereader_friend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ereader_friend
    restart: unless-stopped
    ports:
      - '3001:3001'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
