services:
  book-drop:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: book-drop
    restart: unless-stopped
    ports:
      - '3001:3001'
    cpus: 1.0
    mem_limit: 1g
