services:
  book-drop:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: book-drop
    restart: unless-stopped
    ports:
      - '3001:3001'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
